### ISSUE TITLE
Попробуйте ExtendedItem перевести в functional component

### ISSUE THREAD

**Issue by geshido** [CruelDwemer/Weather-App#2]
Чтобы избавиться от componentDidMount и фильтрации в нём по всем городам в сторе

```js
    selectCity = () => {
        const { cities, match, getWeatherForecast } = this.props;
        const selected = cities.filter(city => city.id === +match.params.id);
        const selectedCity = selected[0];
        this.setState({ selectedCity });
        getWeatherForecast(selectedCity.name);
    }
```

Пусть он все нужные данные для отображения уже получает через `props`

**Comment by CruelDwemer** [comment]
Один нюанс - в таком виде после обновления страницы ExtendedItem данные по городу не отобразятся, т.к. запрос данных происходит при клике на главной странице. Единственно, можно сохранять их в localStorage, но это просто будут последние имеющиеся данные - не обязательно актуальные

**Comment by geshido** [comment]
Попробуйте реализовать выбор города в виде action-а для redux
Это позволит достать свежие данные и положить их в state

**Comment by CruelDwemer** [comment]
К сожалению, так и не смог сообразить, как обойтись без ComponentDidMount, сохраняя возможность компонента восстановить данные после перезагрузки страницы.

**Comment by geshido** [comment]
данные должны загружаться по сигналу из action creator-а и сохраняться в state

компонент берёт данные из стейта

**Comment by CruelDwemer** [comment]
исправил в https://github.com/CruelDwemer/Weather-App/commit/ca9d20106c09aec5f70e3dc16a07a587183dd00d
